In [1]:
import torch
from torch.autograd import Variable

torch.manual_seed(777)

x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],[0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = Variable(torch.Tensor(x_data))
Y = Variable(torch.Tensor(y_data))
nb_classes = 3

softmax = torch.nn.Softmax()
linear = torch.nn.Linear(4,nb_classes, bias = True)
model = torch.nn.Sequential(linear, softmax)

optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

for step in range(2001):
    optimizer.zero_grad()
    hypothesis = model(X)
    cost = -Y*torch.log(hypothesis)
    cost = torch.sum(cost, 1).mean()
    cost.backward()
    optimizer.step()
    
    if step % 200 == 0:
        print(step, cost.data.numpy())
        
print('--------------')
a = model(Variable(torch.Tensor([[1,11,7,9]])))
print(a.data.numpy(), torch.max(a,1)[1].data.numpy())

print('--------------')
b = model(Variable(torch.Tensor([[1, 3, 4, 3]])))
print(b.data.numpy(), torch.max(b, 1)[1].data.numpy())

print('--------------')
c = model(Variable(torch.Tensor([[1, 1, 0, 1]])))
print(c.data.numpy(), torch.max(c, 1)[1].data.numpy())

print('--------------')
all = model(Variable(torch.Tensor([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]])))
print(all.data.numpy(), torch.max(all, 1)[1].data.numpy())

C:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


0 2.3687892
200 0.54633194
400 0.45158783
600 0.37642628
800 0.3045039
1000 0.24127787
1200 0.21791302
1400 0.19881804
1600 0.18269487
1800 0.16890593
2000 0.15698554
--------------
[[7.6587126e-03 9.9233162e-01 9.6463318e-06]] [1]
--------------
[[0.8280994  0.15501583 0.01688474]] [0]
--------------
[[1.3566267e-08 3.5338957e-04 9.9964654e-01]] [2]
--------------
[[7.6587126e-03 9.9233162e-01 9.6463318e-06]
 [8.2809943e-01 1.5501583e-01 1.6884739e-02]
 [1.3566267e-08 3.5338957e-04 9.9964654e-01]] [1 0 2]
